spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quill-db
    username: isa
    password: isaisa
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}