databaseChangeLog:
  - changeSet:
      id: 5-create-vacancy-application
      author: isa
      changes:
        - createTable:
            tableName: vacancy_application
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: user_id
                  type: BIGINT

              - column:
                  name: vacancy_id
                  type: BIGINT

              - column:
                  name: applied_at
                  type: TIMESTAMP

              - column:
                  name: status
                  type: VARCHAR(50)

        - addForeignKeyConstraint:
            baseTableName: vacancy_application
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            constraintName: fk_application_user

        - addForeignKeyConstraint:
            baseTableName: vacancy_application
            baseColumnNames: vacancy_id
            referencedTableName: vacancy
            referencedColumnNames: id
            constraintName: fk_application_vacancy