databaseChangeLog:
  - changeSet:
      id: 3
      author: isa
      changes:
        - createTable:
            tableName: job_application
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: job_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: applied_at
                  type: TIMESTAMP
              - column:
                  name: status
                  type: VARCHAR(50)
        - addForeignKeyConstraint:
            baseTableName: job_application
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            constraintName: fk_application_user
        - addForeignKeyConstraint:
            baseTableName: job_application
            baseColumnNames: job_id
            referencedTableName: job
            referencedColumnNames: id
            constraintName: fk_application_job
        - addUniqueConstraint:
            columnNames: user_id, job_id
            tableName: job_application
            constraintName: uk_user_job